
import com.oi.WordModel;
import com.oi.WordQuestionGenerator;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class TebakNamaWindow extends javax.swing.JFrame {
     WordModel modelWord;    
    List<WordModel> bankSoal;
    String namaPemain;
    int berapakalicoba ;
    int nyawa;
    int hint;
    
    
    /**
     * Creates new form TebakNamaWindow
     */
    public TebakNamaWindow() {
        initComponents();
        
        bankSoal = WordQuestionGenerator.getFile();
        infoLabel.setText("");
        namaAcakLabel.setText("");
        statusLabel.setText("");
        cobaLabel.setText("");
        nilaiLabel.setText("");
        //hintButtton.setText("");
        hintButtton.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mulaiButton = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        namaAcakLabel = new javax.swing.JLabel();
        inputTextField = new javax.swing.JTextField();
        cekButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        cobaLabel = new javax.swing.JLabel();
        nilaiLabel = new javax.swing.JLabel();
        hintButtton = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\tebaknama.png")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Klik Tombol Mulai ! ");

        mulaiButton.setText("Mulai");
        mulaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiButtonActionPerformed(evt);
            }
        });

        infoLabel.setText("Tebak Nama Pemain Bola !");

        namaAcakLabel.setText("jLabel4");

        inputTextField.setEnabled(false);
        inputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTextFieldActionPerformed(evt);
            }
        });

        cekButton.setText("Cek Jawaban");
        cekButton.setEnabled(false);
        cekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekButtonActionPerformed(evt);
            }
        });

        statusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        statusLabel.setText("Status");

        cobaLabel.setText("Coba");

        nilaiLabel.setText("jLabel4");

        hintButtton.setText("Hint");
        hintButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaAcakLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cekButton)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nilaiLabel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                        .addComponent(cobaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mulaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hintButtton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mulaiButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoLabel)
                    .addComponent(hintButtton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaAcakLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cekButton)
                    .addComponent(statusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cobaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nilaiLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateNama(){
        
        
//           
//        String[] namaNama = {"Lionel Messi","Ronaldo","Fabregas","Ronaldinho","Degea","Vidic",
//        "Bambang Pamungkas","David Luiz","Thiago Silva","Maldini"};
//        
//        Random rd = new Random();
//        int index = rd.nextInt(namaNama.length);
//        namaPemain = namaNama[index];
//        namaPemain = namaPemain.toUpperCase();
//        
//        
//        char[] hurufnya = namaPemain.toCharArray();
//        Arrays.sort(hurufnya);
//        String namaAcak = new String(hurufnya);
//        
////        
////        for(int i = 0 ; i < hurufnya.length; i ++){
////            namaAcak += hurufnya[i];
////            
////        }
////        
//        namaAcakLabel.setText(namaAcak);
//        
    }
    
    
    
    private void cekJawaban(){
        try{
            if(inputTextField.getText().equals(""))
                JOptionPane.showMessageDialog(rootPane, "Tidak Boleh Kosong");
            else if(inputTextField.getText().equalsIgnoreCase(namaPemain)){
                
                nilaiLabel.setText("Anda mencoba "+berapakalicoba+ " Kali");
//                
//                        if(berapakalicoba < 4 ){
//                            nilaiLabel.setText("Wah jago ya anda ! ");
//                        }
//                        else if(berapakalicoba > 4 && berapakalicoba >=10 ){
//                            nilaiLabel.setText("Lumayan dehhh ! ");
//                        }
                
                mulaiButton.setEnabled(true);
                inputTextField.setEnabled(false);
                cekButton.setEnabled(false);
            }else{
                cobaLabel.setText("Masih salah !!");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "ERROR !!!!!!");
        }
    }
    
    private void mulaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiButtonActionPerformed
        // TODO add your handling code here:
        
        
        int soalIndex = (int) Math.floor(Math.random() * bankSoal.size());
        System.out.println("Index: " + soalIndex);
        modelWord = bankSoal.get(soalIndex); //bankSoal[soalIndex];
        System.out.println(modelWord.getBasicWord());
        
        namaAcakLabel.setText(modelWord.acakHuruf());
        hint = 2;
        nyawa = 10;
        
        
        infoLabel.setText("Tebak Lah kata - kata ini!");
        hintButtton.setVisible(true);
        inputTextField.setEnabled(true);
        cekButton.setEnabled(true);
        mulaiButton.setEnabled(false);
        statusLabel.setText("");
        cobaLabel.setText("");
        berapakalicoba = 0;
        inputTextField.setText("");
        nilaiLabel.setText("");
    }//GEN-LAST:event_mulaiButtonActionPerformed

    private void inputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTextFieldActionPerformed

    private void cekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekButtonActionPerformed
        // TODO add your handling code here:
        //berapakalicoba++;
        //cekJawaban();
            try{
           String jawaban = inputTextField.getText().trim();
            modelWord.setJawaban(jawaban);
            
         if (modelWord.cekJawaban()) {
            statusLabel.setText("Jenius!");
            mulaiButton.setEnabled(true);
            inputTextField.setEnabled(false);
            cekButton.setEnabled(false);
            hintButtton.setEnabled(false);
            
         } else {
             
             nyawa--;
             if(nyawa == 0){
             cekButton.setEnabled(false);
             mulaiButton.setEnabled(true);
             }
             statusLabel.setText("Coba Lagi"); 
             cobaLabel.setText("Nyawa anda : "+nyawa+ " DOANG BRAY !") ;  
            }
            }catch(Exception e){
                JOptionPane.showConfirmDialog(null, "Inputan Tidak boleh kosong");
            }
    }//GEN-LAST:event_cekButtonActionPerformed

    private void hintButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButttonActionPerformed
        nyawa--;
        
        if(hint == 0 ){
            
            hintButtton.setEnabled(false);
            
        }
        else if(hint == 2){
        hintButtton.setText(modelWord.getHint());
        }
        else if(hint == 1) {
            
        hintButtton.setText(modelWord.getHint2());
        hintButtton.setEnabled(false);
        }
        
        if(nyawa == 0){
         
        cekButton.setEnabled(false);
         mulaiButton.setEnabled(true);
         }
        cobaLabel.setText("Nyawa anda : "+nyawa+ " DOANG BRAY !") ;
        hint--;
             
                 // TODO add your handling code here:
    }//GEN-LAST:event_hintButttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TebakNamaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TebakNamaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TebakNamaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TebakNamaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TebakNamaWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cekButton;
    private javax.swing.JLabel cobaLabel;
    private javax.swing.JButton hintButtton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JTextField inputTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mulaiButton;
    private javax.swing.JLabel namaAcakLabel;
    private javax.swing.JLabel nilaiLabel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
